trigger: none
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    name: mvnsettings
    inputs:
      secureFile: 'mvnsettings'    # Name of the file in Azure Library Secure Files

  - script: |
      echo "Using secure settings.xml from: $(mvnsettings.secureFilePath)"
      mvn clean package -s $(mvnsettings.secureFilePath)
    displayName: 'Maven Build with Secure settings.xml'
