trigger: none

variables:
  - group: JAVAVAR

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Printing all variables from JAVAVAR"
      echo "VAR1 = $(VAR1)"
      echo "VAR2 = $(VAR2)"
      echo "VAR3 = $(VAR3)"
    displayName: 'Print JAVAVAR variables'
