trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: destroy
    displayName: 'Destroy Infrastructure'
    type: boolean
    default: false

steps:
  - task: AzureCLI@2
    displayName: Lint Bicep
    condition: eq('${{ parameters.destroy }}', false)
    inputs:
      azureSubscription: 'azarm'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az bicep build --file main.bicep'
      workingDirectory: '$(System.DefaultWorkingDirectory)/bicep'

  - task: AzureCLI@2
    displayName: Validate Bicep
    condition: eq('${{ parameters.destroy }}', false)
    inputs:
      azureSubscription: 'azarm'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub validate \
          --location eastus \
          --template-file main.bicep
      workingDirectory: '$(System.DefaultWorkingDirectory)/bicep'

  - task: AzureCLI@2
    displayName: What-If (Plan) Bicep
    condition: eq('${{ parameters.destroy }}', false)
    inputs:
      azureSubscription: 'azarm'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub what-if \
          --location eastus \
          --template-file main.bicep
      workingDirectory: '$(System.DefaultWorkingDirectory)/bicep'

  - task: AzureCLI@2
    displayName: Apply Bicep
    condition: eq('${{ parameters.destroy }}', false)
    inputs:
      azureSubscription: 'azarm'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment sub create \
          --location eastus \
          --name bicep-demo-deployment \
          --template-file main.bicep
      workingDirectory: '$(System.DefaultWorkingDirectory)/bicep'

  - task: AzureCLI@2
    displayName: Clean Up (Destroy)
    condition: eq('${{ parameters.destroy }}', true)
    inputs:
      azureSubscription: 'azarm'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az group delete --name demo-rg --yes --no-wait'
      workingDirectory: '$(System.DefaultWorkingDirectory)/bicep'