trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Az-connect'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo " Logging into acr"
      az acr login -n mevijay
      docker build -t mevijay.azurecr.io/hello-java:$(Build.BuildId) . -f stagedockerbuild.dockerfile 
      docker push mevijay.azurecr.io/hello-java:$(Build.BuildId)
- task: HelmDeploy@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Az-connect'
    azureResourceGroup: 'dev'
    kubernetesCluster: 'myaks'
    useClusterAdmin: true
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: './helm'
    releaseName: 'myapp'
    namespace: 'default'
    overrideValues: 'image.tag=$(Build.BuildId)'
